import { LIBRARY_ACTION, LIBRARY_FILE_TYPE } from "../../enums";

export const ROOT_ACTIONS: LIBRARY_ACTION[] = [
  LIBRARY_ACTION.ADD_FILE,
  LIBRARY_ACTION.ADD_FOLDER,
];

export const ADD_TYPES: LIBRARY_FILE_TYPE[] = [
  LIBRARY_FILE_TYPE.IMAGE,
  LIBRARY_FILE_TYPE.TEXTURE_ATLAS,
];
